### ISSUE TITLE
com.epam.reportportal.service.ReportPortal.Builder.buildEndpointUrl assumes all endpoints should be in v2 when running with async reporting

### ISSUE THREAD

**Issue by tzahialt** [reportportal/client-java#145]
com.epam.reportportal.service.ReportPortal.Builder.buildEndpointUrl assumes all endpoints should be in v2 when running with async reporting.
This is not true for endpoints such as com.epam.reportportal.service.ReportPortalClient#getLaunchByUuid. Trying to invoke it when com.epam.reportportal.listeners.ListenerParameters#isAsyncReporting is true, results in HTTP error 404, due to the incorrect use of API_V2_BASE.

In my specific scenario, I found a work-around, in the form of creating a separate ReportPortalClient with a clone of my ListenerParameters, where i tweaked setAsyncReporting(false), so i was able to successfully invoke com.epam.reportportal.service.ReportPortalClient#getLaunchByUuid from this dedicated client.

**Comment by HardNorth** [comment]
@tzahialt I just released new version of the client, where this issue is addressed:
https://github.com/reportportal/client-java/releases/tag/5.1.0-BETA-1

**Comment by HardNorth** [comment]
And I'm going to add more API V1 endpoints late.

**Comment by amalbaccar-hub** [comment]
Hello @HardNorth 

Faced similar issue : **got 404 for getLaunchByUuid for v1**

Response{protocol=http/1.1, code=404, message=Not Found, url=http://rp-url/api/v1/superadmin_personal/launch/uuid/5cfcf5aa-5cdd-4ca5-ac96-7176f22e6133}

Could you please add endpoints to V1

**Comment by HardNorth** [comment]
@amalbaccar-hub, this is V1 only endpoint. So please check how you obtain this UUID. Also, Launch creation is async process, so you have to implement some sort of waiter, if you call for the Launch info on the very start.

PS: Please do not post in to such an old issue. I any case this will be off-topic.
