### ISSUE TITLE
Retrieve suiteNumber to build URL

### ISSUE THREAD

**Issue by kburdo** [reportportal/client-java#152]
I want to generate url to new suite after creation of it using client-java library (client-java:5.0.18, commons-model:5.3.3). I use the following template

{base_uri}/ui/{project}/launches/all/{**launchNumber**}/{**suiteNumber**}

launchNumber - to get it we call `com.epam.reportportal.service.ReportPortalClient#getLaunchByUuid` and use `LaunchResource#launchId` field

Is there any way to retrieve suiteNumber?

**Comment by HardNorth** [comment]
@kburdo No, at least for now.
