### ISSUE TITLE
Accept or trim NestedSteps name longer than 1024 symbols without throwing the error

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/client-java#154]
We use - https://github.com/reportportal/client-java
So, @evjlobanova : if you'll have a close look at the screenshot
![image](https://user-images.githubusercontent.com/50797731/115390005-64817100-a1fb-11eb-9f60-4d0106bcd761.png)

Line 378 is missing in RP logs, however, all other lines are been captured. So it was a lengthy step at line number 378 which failed and was not captured in the logs.

_Originally posted by @priyankachaturvedi30 in https://github.com/reportportal/reportportal/issues/1359#issuecomment-823206431_

**Comment by priyankachaturvedi30** [comment]
@DzmitryHumianiuk : Thanks for opening up this as a separate thread. Are we considering this use case for implementation?

**Comment by HardNorth** [comment]
@DzmitryHumianiuk What is going to be expected behavior in this case? Truncation with `...` ?

**Comment by HardNorth** [comment]
> @DzmitryHumianiuk What is going to be expected behavior in this case? Truncation with `...` ?

OK, looks so.

**Comment by HardNorth** [comment]
Released: https://github.com/reportportal/client-java/releases/tag/5.0.22
