### ISSUE TITLE
I need to get the launch id when saving it in the report portal

### ISSUE THREAD

**Issue by marcelbraghini** [reportportal/client-java#180]
Hey guys

I'm needing to get the id of a launch when I save it there in the report portal
I was taking a look here LaunchImpl.java (on line 112), after generating a new launch is it possible to generate a log to print the launch id or number in the terminal?

**Comment by marcelbraghini** [comment]
I can do something like:

LaunchImpl > finish()

```java
Maybe<LaunchResource> maybeRs = client.getLaunchByUuid(uuid);

    if (maybeRs != null) {
	    System.out.println("Launch ID ReportPortal: " + maybeRs.blockingGet().getLaunchId());
    }
```

the info loggers are not presented in the terminal either, is there any way to do this without using a println?

**Comment by HardNorth** [comment]
@marcelbraghini Well, you can do it with any Logger you use on your project. Logging into terminal is just a matter of your configuration and nothing else.
