### ISSUE TITLE
Access the response of `/api/{version}/{projectName}/launch` in Tests

### ISSUE THREAD

**Issue by badrinrs** [reportportal/client-java#181]
Hi.

I would like to store launch_uuid and number for future reference to update test results. Can you please advise how I can get the details. I am using agent-java-cucumber in my tests.

**Comment by DzmitryHumianiuk** [comment]
@HardNorth what do you thing about static utilities in client, which can return this information?

**Comment by HardNorth** [comment]
Already implemented, but not released: https://github.com/reportportal/client-java/blob/develop/CHANGELOG.md#unreleased

**Comment by badrinrs** [comment]
@HardNorth Can you please advise when the next version is planned for release?
