### ISSUE TITLE
Getting  error "Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener"

### ISSUE THREAD

**Issue by anirbanpuky** [reportportal/client-java#182]
While running the test in Azure Devops Pipeline, I am getting the below error 
"Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener" 
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process

I have mentioned the listener in my POM.xml file only.
Please help.

Dependencies :

            <dependency>
                <groupId>com.epam.reportportal</groupId>
                <artifactId>agent-java-testng</artifactId>
                <version>5.1.1</version>
            </dependency>
            <dependency>
                <groupId>com.epam.reportportal</groupId>
                <artifactId>logger-java-log4j</artifactId>
                <version>5.1.4</version>
            </dependency>

**Comment by HardNorth** [comment]
@iKabi @anirbanpuky I transferred your issue into `client-java` since this is not a TestNG agent issue.
Well it look like you have `agent.jobstatus` and `AGENT_JOBSTATUS` keys in your environment variables simultaneously. This is rather unusual, but I fixed that.
