### ISSUE TITLE
Many launches when ReuseFork is set on false

### ISSUE THREAD

**Issue by mbanacho** [reportportal/client-java#192]
1) Problem description:
When we run test with maven-surefire-plugin with flag reuseForks set on FALSE than we have many launches. From my analysis I know that first thread is creating PrimaryLaunch object and second thread is creating SecondaryLaunch. Problem occurs when test from PrimaryLaunch finish, than fork is killed by maven surefire and lock file is removed. Because of that next test is starting new lock and new PrimaryLaunch.
2) tech spec
java 1.8
<groovy.version>2.4.15</groovy.version>
<spock.version>1.2-groovy-2.4</spock.version>
Maven surefire plugin

```<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M6</version>
        <configuration>
          <trimStackTrace>false</trimStackTrace>
          <forkCount>2</forkCount>
          <reuseForks>false</reuseForks>
        </configuration>
      </plugin>
```

ReportPortal dependencies:

 ```   <dependency>
      <groupId>com.epam.reportportal</groupId>
      <artifactId>agent-java-spock</artifactId>
      <version>5.1.0-RC-5</version>
      <exclusions>
        <exclusion>
          <groupId>com.epam.reportportal</groupId>
          <artifactId>client-java</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.epam.reportportal</groupId>
      <artifactId>client-java</artifactId>
      <version>5.1.10</version>
    </dependency>
```
3) tested solutions
3.1)I tried to create launch manually put uuid of it into lock file but without success, I got timeouts and my lock file was override.
That solution stuck here:
```public String obtainLaunchUuid(@Nonnull final String instanceUuid) {
		Objects.requireNonNull(instanceUuid);
		if (mainLock != null) {
			if (!instanceUuid.equals(lockUuid)) {
				writeInstanceUuid(instanceUuid);
			}
			return lockUuid;
		}
		Pair<RandomAccessFile, FileLock> syncLock = obtainLock(syncFile);
		if (syncLock != null) {
			try {
				if (mainLock == null) {
					Pair<RandomAccessFile, FileLock> lock = obtainLock(lockFile);
					if (lock != null) {
						// we are the main thread / process
						lockUuid = instanceUuid;
						mainLock = lock;
						writeLaunchUuid(syncLock);
						return instanceUuid;
					} else {
						executeOperation(new LaunchRead(instanceUuid), syncLock);
					}
				} else {
					// another thread obtained main lock while we wait for .sync file
					executeOperation(new UuidAppend(instanceUuid), syncLock);
					return lockUuid;
				}
			} finally {
				closeIo(syncLock);
			}
			// main lock file already locked, just close sync lock and proceed with secondary launch logic
		}
		return obtainLaunch(instanceUuid);```
3.2) change rp.client.join.lock.timeout.value but it is not resistant for killing fork by plugin

Could You look at this case ?

**Comment by HardNorth** [comment]
There is no way to find out inside such fork whether the test is running within one launch or in separate launches, so automatic launch join in such case is impossible.

Alternatively, since you create a launch manually, you also need to create `reportportal.lock` and `reportportal.sync` files with launch UUID at the first line and hold file system lock on `reportportal.lock` file till the end of the execution. This will tell other forks that they are 'secondary' and the will not try to override and start separate launches.
