### ISSUE TITLE
Separate report portal properties file according to the environment(Stg,QA,DEV)

### ISSUE THREAD

**Issue by php-del** [reportportal/client-java#198]
Is there any way we can configure our code to use reportportal.properties file according to our environment? Means we pass environment value from pom.xml whether staging or QA but we have only single reportportal.properties file being used. Can we use two separate properties files? Is any documentation available for this?

**Comment by HardNorth** [comment]
@php-del There is no special property to override property file name right now. I'll consider later implementation.

**Comment by HardNorth** [comment]
Implemented: https://github.com/reportportal/client-java/releases/tag/5.1.14
