### ISSUE TITLE
[Improve] Add for @TestCaseID abilities to add TMS link

### ISSUE THREAD

**Issue by tronstone** [reportportal/client-java#204]
**Is your feature request related to a problem? Please describe.**
I would like to be able to link from the reportportal to a test case in the TMS

**Describe the solution you'd like**
Provide markdown for @TestCaseID or better way make some customizer where I can say, that for all $test_case_id replace as `https://tms.com/test_case_id`. In RP it should looks like link with test_case_id

**Comment by HardNorth** [comment]
@tronstone I don't personally like your suggestion, we have our own mechanisms to link RP to TMS issues. E.G. through Issue. And I don't like the idea of making Allure from RP.

**Comment by tronstone** [comment]
@HardNorth I don't really understand how I can link to a test case in TMS via a link issue. API doesn't allow to attach TMS link to PASSED, and API as a whole looks weird, it's obviously made for BTS and not for TMS:

![image](https://user-images.githubusercontent.com/75780254/232023534-47bd4602-3cfa-427d-9e6e-685194d86b57.png)

I thought it was possible by reading this documentation: https://reportportal.io/docs/work-with-reports/TestCaseId/#what-is-it-test-case-id.

But no, you can't attach a link to the TMS through this mechanism. So I created a request for this function. If you know another way, please suggest it.

P.S Report Portal is better than allure in everything, but this particular feature from allure is still missing.
