### ISSUE TITLE
[Improve] Add the ability to call methods in the @Step annotation

### ISSUE THREAD

**Issue by tronstone** [reportportal/client-java#210]
In [Add more sources to Step annotaion](https://github.com/reportportal/client-java/issues/70) issue a lot of work has been done, thanks to all the developers who participated in this request. But as far as I understand from the documentation and what I tried in practice, the possibility to call parameter methods has never been implemented.

Is it possible to add the following feature:

```java
@Step("Asserting '{dataCheckEntry.getKey()}' year")
private void assertYear(Map.Entry<Integer, String> dataCheckEntry) { // method entry just for example
    // Some step code
}
```

**Comment by HardNorth** [comment]
@tronstone Implemented in: https://github.com/reportportal/client-java/releases/tag/5.2.18
