### ISSUE TITLE
Ignore SSL verification

### ISSUE THREAD

**Issue by ABHammad** [reportportal/client-java#249]
**Is your feature request related to a problem? Please describe.**
I am using Junit5 and RestAssured, but failed to report data to the log because SSL handshake verification 
and I can't ignore it  by property "verify_ssl"

**Describe the solution you'd like**
I would like to add a property to control in verification 

I tried to make a PR but there are some tests are failing already in master branch when I run `./gradlew clean build`

**Comment by ABHammad** [comment]
@HardNorth

**Comment by HardNorth** [comment]
@ABHammad Java is not Python, it has different guidelines and traditions of what is acceptable or not in the code. And there is strong a tradition not to encourage users to bypass best security practices. So I will not introduce such property here in any case. If you need it, read corresponding documents of how to implement SSL verification bypassing for OkHttp (our http client), E.G. [here](https://stackoverflow.com/questions/25509296/trusting-all-certificates-with-okhttp). Without any further comments how exactly this should be done in ReportPortal code.

Or a way better solution is to import your custom certificate to local truststore: https://stackoverflow.com/questions/9619030/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatore

**Comment by ABHammad** [comment]
just as a solution for that issue.
it is solved by creating jks file and adde dit in the properties file 

here are the. two properties
rp.keystore.resource=./resources/keystore.jks
rp.keystore.password=changeit
