### ISSUE TITLE
Header name Case issue

### ISSUE THREAD

**Issue by yurigava** [reportportal/client-java#28]
Hi,
I am having issues caused by this line.
https://github.com/reportportal/client-java/blob/82b3840c9533528e59384c9621d84b5c14d0da37/src/main/java/com/epam/reportportal/service/ReportPortalErrorHandler.java#L127
For some reason the server sets the header to "content-type", this is not an issue, since the RFC states field names are case-insensitive: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
The code tries to get the value from the map, but nothing is returned, this causes an error in the execution:
[ERROR] [93] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 201
Status message: Created
Error Message: 
Error Type: null

The Launch is created, but no other request is sent (would make sense, if there was an actual error).

I think the solution might be using CaseInsensitiveMap.
Is there a workaround?

**Comment by DzmitryHumianiuk** [comment]
@yurigava now we can close it?

**Comment by yurigava** [comment]
Sure. Thanks.
