### ISSUE TITLE
Can we remove Skipped test cases from report generated and sent via email after launch ?

### ISSUE THREAD

**Issue by Mandeep-S** [reportportal/client-java#30]
I am implementing IRetryAnalyzer interface and when one test case fails and retry for second time, Report portal counts it as a new test in the report. Is there a way to handle this ?

**Comment by filland** [comment]
@Mandeep-S hi, what language (java, js, etc.) do you use ?

**Comment by filland** [comment]
@Mandeep-S hi, seems like you are working with TestNG, right ?

**Comment by Mandeep-S** [comment]
> @Mandeep-S hi, seems like you are working with TestNG, right ?

Yes, I have implemented a Listener class as well which takes care of scenarios where if a test fails it will try for 2 times.

**Comment by filland** [comment]
@Mandeep-S  do you know that we already have a lib that integrates reportportal with testng ?
You can find it here
https://github.com/reportportal/agent-java-testNG
By the way, retries are supported in this lib.

**Comment by Mandeep-S** [comment]
@filland Thanks, I used some code from ReportPortal TestNG listener and solved some of the concerns that I have. Can you point me to the class which is taking care of email message ? I want to customize message.

**Comment by filland** [comment]
@Mandeep-S Email message ? Could you provide more details ?

**Comment by Mandeep-S** [comment]
@filland The launch status message that we get over email. In ReportPortal, we can setup email notification after a launch which includes details like Total run, passed, failed, etc test case count. So, I want to customize that message details. If you have any insight or code which is taking care of it, please point to it.

**Comment by filland** [comment]
@Mandeep-S I got you. Unfortunately there is not way to customize the content of the email since its template is located in the api service of RP.
