### ISSUE TITLE
Add information after test

### ISSUE THREAD

**Issue by Sadknight** [reportportal/client-java#4]
Please add id launch after test

**Comment by avarabyeu** [comment]
@Sadknight where you want id to be added?

**Comment by Sadknight** [comment]
In temp file.

**Comment by DzmitryHumianiuk** [comment]
@Sadknight not really clear request for now.
Could you please describe in details?

**Comment by Sadknight** [comment]
@DzmitryHumianiuk 
У нас тесты стартуют из таски в Jira, в один момент времени таких запусков может быть много. Мне необходимо вернуть результаты прогона и ссылку на launch в Jira.
Я так понял это можно сделать только по id запуска к которому у меня нет доступа.

**Comment by DzmitryHumianiuk** [comment]
@Sadknight id запуска будет знать агент, который выполняет запуск.
Сложно представляю как именно у вас запускаются тесты из таски в джире,
но если у вас есть какая-то своя прослойка написанная, то она может и забирать ID из агента репорт портального.
и из этого id формировать ссылку в виде `http://СЕРВЕР/ui/#ПРОЕКТ/launches/all/ID`

**Comment by Sadknight** [comment]
@dzmitryhumianiuk
Могу показать, если интересно. 
Когда можно ожидать добавления?

**Comment by DzmitryHumianiuk** [comment]
@Sadknight пока не сильно понятно. поэтому и сроков никаких сказать не могу.

ну и это скорее доработка агента, на вашей стороне.
не серверное изменение.

найди меня в нашем слэке.
https://reportportal-slack-auto.herokuapp.com/

**Comment by avarabyeu** [comment]
This is client-side change and actually it may be helpful for Jenkins plugin which is also need this functionality. Makes sense.

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/client-java/commit/8a0b07e01f3ceffd01e90c5653b81f2979852b65

**Comment by DzmitryHumianiuk** [comment]
resolved
