### ISSUE TITLE
[Improve] Add @Issue annotation

### ISSUE THREAD

**Issue by Zahorodnii** [reportportal/client-java#72]
Create logic for link Issues from java for tests like Allure but with integration JIRA plugin.

**reportportal.properties**

```properties
rp.btsUrl =https://jira.services.com/
rp.issuesUrl = browse
rp.btsProject = EXPL
```
@Test
@Issue("4211")
public void test() { }

Where issue value will be EXPL-4211 with issue URL https://jira.services.com/browse/EXPL-4211.

For TestNG implementation can be added Skip Exception while test marked by @Issue annotation or Issue have status OPEN, IN PROGRESS, or add logic for setup status when test will finish throwing Skip Exception.

**Comment by HardNorth** [comment]
https://github.com/reportportal/client-java/blob/develop/src/main/java/com/epam/reportportal/annotations/Issue.java
