### ISSUE TITLE
Add possibility to use custom launch ID in client.

### ISSUE THREAD

**Issue by Vitovtx** [reportportal/client-java#8]
Custom launch ID could be used with following scenarios:
1. Several regression suites are launched in different time. All of them reports to the same single launch on Report Portal.
2. Performance testing - parallel regression suites run from several computers that report to the same single Report Portal launch.
Pull requests with code example:
[agent-java-cucumber](https://github.com/reportportal/agent-java-cucumber/pull/6)
[client-java](https://github.com/reportportal/client-java/pull/7)

**Comment by avarabyeu** [comment]
I bit changed, but added:
https://github.com/reportportal/client-java/blob/4.0.x/src/main/java/com/epam/reportportal/service/ReportPortal.java#L110
