### ISSUE TITLE
messages not logged in report portal for multi thread

### ISSUE THREAD

**Issue by willyhalim** [reportportal/client-java#91]
Whenever messages are are logged from different thread , its not logged in report portal

```
 @Test
    public void test(){

        //message logged properly
        LOGGER.info("test start");

        //not logged in reportportal
        Runnable test = () -> {
            LOGGER.info("incoming message");
        };

        new Thread(test).start();

        LOGGER.info("test done");
    }
```

Not too sure if the issues is due internally it uses ThreadLocal
https://github.com/reportportal/client-java/blob/develop/src/main/java/com/epam/reportportal/service/LoggingContext.java#L55

**Comment by HardNorth** [comment]
Well, yes, this is due to ThreadLocal. And currently we can't change such design. Probably we wil redesign it in later versions.

**Comment by HardNorth** [comment]
Duplicates another issue, which has stronger justification: https://github.com/reportportal/client-java/issues/105
