### ISSUE TITLE
Logs from Listener attached to Test level instead of Test Method level (@Test) in case of fail in Step

### ISSUE THREAD

**Issue by maxski** [reportportal/client-java#97]
Pre-conditions:
1. TestWithStep where Step has failure
2. TestWithoutStep where Test itself has failure
3. Listener should add logs in case of fail.

Scenario:
1. Run both tests.

**Expected behavior:** Both tests has listener logs on Test Method level.
**Actual behavior**: TestWithoutStep has logs on Test Method level. But TestWithStep doesn't have logs on Test Method level, instead they appears on Test level.

Project for reproduction: https://github.com/maxski/rp-fail-in-step

**Comment by HardNorth** [comment]
Fixed with: https://github.com/reportportal/client-java/pull/98
